"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {fibLevels} from '@/lib/fibonacci';
import type {Drawing} from '@/lib/session-schema';
export default function FibStyleSettings({drawing,onApply}:{drawing:Drawing;onApply:(patch:Partial<Drawing>)=>void}){
 const [levels,setLevels]=useState(()=>fibLevels(drawing.fibLevels).map(level=>({...level,value:String(level.value),color:level.color??drawing.color})));
 const [color,setColor]=useState(drawing.color),[width,setWidth]=useState(drawing.lineWidth??2),[opacity,setOpacity]=useState(drawing.opacity??.06),[dashed,setDashed]=useState(drawing.dashed),[options,setOptions]=useState(drawing.fibOptions??{showPrices:true,showRatios:true,showTrendLine:true});
 const valid=levels.every(level=>level.value.trim()!==''&&Number.isFinite(Number(level.value)));
 return <div className="fib-settings"><div className="fib-global-style"><label>默认颜色<input aria-label="斐波那契默认颜色" type="color" value={color} onChange={e=>{setColor(e.target.value);setLevels(list=>list.map(level=>({...level,color:e.target.value})));}}/></label><label>线宽<select aria-label="斐波那契线宽" value={width} onChange={e=>setWidth(Number(e.target.value))}>{[1,2,3,4].map(n=><option value={n} key={n}>{n}px</option>)}</select></label><label>填充透明度<Input aria-label="斐波那契填充透明度" type="number" min="0" max="1" step=".01" value={opacity} onChange={e=>{const n=Number(e.target.value);if(n>=0&&n<=1)setOpacity(n);}}/></label><label><input type="checkbox" checked={dashed} onChange={e=>setDashed(e.target.checked)}/>虚线</label></div><div className="fib-label-options">{([['showPrices','显示价格'],['showRatios','显示比例'],['showTrendLine','显示趋势线']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={options[key]} onChange={e=>setOptions({...options,[key]:e.target.checked})}/>{label}</label>)}</div><p className="fib-help">0–1：内部回撤 · 大于 1：外部回撤 · 小于 0：扩展。0 和 1 对应两个原始锚点。</p><div className="fib-level-grid">{levels.map((level,i)=><div className="fib-level-row" key={i}><input type="checkbox" aria-label={`显示水平 ${i+1}`} checked={level.enabled} onChange={e=>setLevels(list=>list.map((item,j)=>j===i?{...item,enabled:e.target.checked}:item))}/><Input aria-label={`水平 ${i+1} 比例`} type="text" inputMode="decimal" value={level.value} onChange={e=>setLevels(list=>list.map((item,j)=>j===i?{...item,value:e.target.value}:item))}/><input type="color" aria-label={`水平 ${i+1} 颜色`} value={level.color} onChange={e=>setLevels(list=>list.map((item,j)=>j===i?{...item,color:e.target.value}:item))}/></div>)}</div>{!valid&&<p role="alert">请为每个水平输入有效数字。</p>}<Button disabled={!valid} onClick={()=>onApply({color,lineWidth:width,opacity,dashed,fibOptions:options,fibLevels:levels.map(level=>({...level,value:Number(level.value)}))})}>应用样式与比例</Button></div>;
}
