"use client";
import {useEffect,useRef,useState} from 'react';
import {createChart,createSeriesMarkers,CandlestickSeries,HistogramSeries,LineSeries,ColorType,type IChartApi,type ISeriesApi,type ISeriesMarkersPluginApi,type Time,type UTCTimestamp,type Logical} from 'lightweight-charts';
import {fibLevels,fibPrice} from '@/lib/fibonacci';
import {prependedBars} from '@/lib/history-series';
import {average,type Candle} from '@/lib/replay';
import type {Drawing} from '@/lib/session-schema';
import {timeToLogical,logicalToTime,translateDrawing} from '@/lib/drawing-geometry';
import type {TradeFill} from '@/lib/okx';
export type Tool='cursor'|Drawing['type']|'pick';
type Point={time:number;price:number};
type Props={onLoadOlder?:()=>void;candles:Candle[];period:number;cursor:number;drawings:Drawing[];fills:TradeFill[];showFills:boolean;tool:Tool;color:string;dashed:boolean;snap:boolean;ma:boolean;ema:boolean;selected:string|null;onSelect:(id:string|null)=>void;onDraw:(drawing:Drawing)=>void;onChange:(drawing:Drawing)=>void;onEditStart:()=>void;onCancel:()=>void;onPick:(time:number)=>void;resetKey:string;onHover:(c:Candle|null)=>void;text:string};
export default function ReplayChart(p:Props){
 const host=useRef<HTMLDivElement>(null),chart=useRef<IChartApi|null>(null),series=useRef<ISeriesApi<'Candlestick'>|null>(null),volume=useRef<ISeriesApi<'Histogram'>|null>(null),maLine=useRef<ISeriesApi<'Line'>|null>(null),emaLine=useRef<ISeriesApi<'Line'>|null>(null),fillMarkers=useRef<ISeriesMarkersPluginApi<Time>|null>(null),latest=useRef(p);latest.current=p;
 const [size,setSize]=useState({w:800,h:500}),[,redraw]=useState(0),[points,setPoints]=useState<Point[]>([]),[hover,setHover]=useState<Point|null>(null),[drag,setDrag]=useState<{id:string;index:number;start:Point;original:Drawing}|null>(null);
 const [textEditor,setTextEditor]=useState<{drawing:Drawing;value:string;existing:boolean}|null>(null);
 useEffect(()=>{setTextEditor(null);},[p.period,p.resetKey]);
 function commitText(){if(!textEditor?.value.trim())return;const drawing={...textEditor.drawing,text:textEditor.value.trim()};if(textEditor.existing){p.onEditStart();p.onChange(drawing);}else p.onDraw(drawing);setTextEditor(null);}
 const lastReset=useRef(''),previousBars=useRef<Candle[]>([]);
 useEffect(()=>{if(!host.current)return;const c=createChart(host.current,{autoSize:true,layout:{background:{type:ColorType.Solid,color:'#ffffff'},textColor:'#787b86',fontSize:12,fontFamily:'Inter, system-ui, sans-serif',attributionLogo:false},grid:{vertLines:{color:'#f0f1f4'},horzLines:{color:'#f0f1f4'}},crosshair:{mode:0,vertLine:{color:'#000000',style:2,labelBackgroundColor:'#000000'},horzLine:{color:'#000000',style:2,labelBackgroundColor:'#000000'}},rightPriceScale:{borderColor:'#434651',scaleMargins:{top:.16,bottom:.24}},timeScale:{borderColor:'#434651',timeVisible:true,secondsVisible:false,shiftVisibleRangeOnNewBar:false,rightOffset:12,barSpacing:7,minBarSpacing:2,tickMarkFormatter:(t:number)=>new Date(t*1000).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})},localization:{timeFormatter:(t:number)=>new Date(t*1000).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}});
 chart.current=c;series.current=c.addSeries(CandlestickSeries,{upColor:'#089981',downColor:'#f23645',borderVisible:false,wickUpColor:'#089981',wickDownColor:'#f23645',priceLineColor:'#000000'});fillMarkers.current=createSeriesMarkers(series.current,[],{autoScale:true,zOrder:'top'});volume.current=c.addSeries(HistogramSeries,{priceFormat:{type:'volume'},priceScaleId:'volume',lastValueVisible:false,priceLineVisible:false});volume.current.priceScale().applyOptions({scaleMargins:{top:.84,bottom:.02}});maLine.current=c.addSeries(LineSeries,{color:'#f6b94b',lineWidth:1,lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false});emaLine.current=c.addSeries(LineSeries,{color:'#7b61ff',lineWidth:1,lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false});
 const refresh=()=>redraw(v=>v+1);const historyRange=(range:{from:number;to:number}|null)=>{refresh();if(range&&range.from<80)latest.current.onLoadOlder?.();};c.timeScale().subscribeVisibleLogicalRangeChange(historyRange);c.subscribeCrosshairMove(param=>{const d=param.seriesData.get(series.current!);latest.current.onHover(d&&'close'in d?d as unknown as Candle:null);});const ro=new ResizeObserver(entries=>{const r=entries[0].contentRect;setSize({w:r.width,h:r.height});refresh();});ro.observe(host.current);host.current.addEventListener('pointermove',refresh);host.current.addEventListener('wheel',refresh);const element=host.current;return()=>{element.removeEventListener('pointermove',refresh);element.removeEventListener('wheel',refresh);ro.disconnect();c.remove();chart.current=null;};},[]);
 useEffect(()=>{const c=chart.current,s=series.current;if(!c||!s)return;const viewport=c.timeScale().getVisibleLogicalRange();const cast=p.candles.map(x=>({...x,time:x.time as UTCTimestamp}));const before=previousBars.current;const incremental=before.length>0&&cast.length>=before.length&&before.slice(0,-1).every((bar,i)=>{const next=cast[i];return next&&bar.time===next.time&&bar.open===next.open&&bar.high===next.high&&bar.low===next.low&&bar.close===next.close&&bar.volume===next.volume;});if(incremental){for(const bar of cast.slice(before.length-1))s.update(bar);}else s.setData(cast);const volumeBars=cast.map(x=>({time:x.time,value:x.volume,color:x.close>=x.open?'#08998142':'#f2364542'}));if(incremental){for(const bar of volumeBars.slice(before.length-1))volume.current?.update(bar);}else volume.current?.setData(volumeBars);previousBars.current=p.candles;maLine.current?.setData(p.ma?average(p.candles,20).map(x=>({...x,time:x.time as UTCTimestamp})):[]);emaLine.current?.setData(p.ema?average(p.candles,50,true).map(x=>({...x,time:x.time as UTCTimestamp})):[]);c.timeScale().applyOptions({minBarSpacing:p.period===1440?.12:2});const key=p.resetKey+':'+p.period;if(cast.length&&key!==lastReset.current){c.timeScale().fitContent();lastReset.current=key;}else if(cast.length&&viewport)c.timeScale().setVisibleLogicalRange({from:viewport.from+Math.max(0,prependedBars(before,p.candles)),to:viewport.to+Math.max(0,prependedBars(before,p.candles))});redraw(v=>v+1);},[p.candles,p.period,p.resetKey,p.ma,p.ema]);
 useEffect(()=>{const markers=fillMarkers.current;if(!markers)return;if(!p.showFills){markers.setMarkers([]);return;}const barTimes=new Set(p.candles.map(bar=>bar.time));markers.setMarkers(p.fills.filter(fill=>fill.time<=p.cursor).flatMap(fill=>{const time=Math.floor(fill.time/(p.period*60))*p.period*60;if(!barTimes.has(time))return [];return [{time:time as UTCTimestamp,position:fill.side==='buy'?'atPriceBottom' as const:'atPriceTop' as const,price:fill.price,shape:fill.side==='buy'?'arrowUp' as const:'arrowDown' as const,color:fill.side==='buy'?'#55e6b3':'#ff7188',text:`${fill.side==='buy'?'买':'卖'} ${fill.size.toLocaleString('en-US',{maximumSignificantDigits:5})}`,size:1.4}];}));},[p.fills,p.showFills,p.cursor,p.period,p.candles]);
 useEffect(()=>{setPoints([]);setHover(null);setDrag(null);chart.current?.applyOptions({handleScroll:p.tool==='cursor',handleScale:p.tool==='cursor'});},[p.tool,p.period,p.resetKey]);
 function indexOf(t:number){return timeToLogical(p.candles,t,p.period);}
 function xy(point:Point){return{x:chart.current?.timeScale().logicalToCoordinate(indexOf(point.time) as Logical)??-1000,y:series.current?.priceToCoordinate(point.price)??-1000};}
 function toPoint(e:React.PointerEvent<SVGSVGElement>):Point|null{if(!chart.current||!series.current||!p.candles.length)return null;const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(x>(chart.current?.timeScale().width()??size.w-72)||y>size.h-28)return null;const index=chart.current.timeScale().coordinateToLogical(x);const price=series.current.coordinateToPrice(y);if(index==null||price==null||price<=0)return null;const i=Math.round(Number(index)),clamp=Math.min(p.candles.length-1,Math.max(0,i)),bar=p.candles[clamp];const time=logicalToTime(p.candles,Number(index),p.period);let value:number=price;if(p.snap&&i>=0&&i<p.candles.length){const nearest=[bar.open,bar.high,bar.low,bar.close].sort((a,b)=>Math.abs(a-price)-Math.abs(b-price))[0];if(Math.abs((series.current.priceToCoordinate(nearest)??-1000)-y)<=12)value=nearest;}return{time,price:value};}
 function down(e:React.PointerEvent<SVGSVGElement>){if(p.tool==='cursor')return;const point=toPoint(e);if(!point)return;if(p.tool==='pick'){p.onPick(Math.min(p.cursor,point.time+p.period*60));p.onCancel();return;}if(p.tool==='text'){setTextEditor({drawing:{id:crypto.randomUUID(),type:'text',points:[point],createdAt:p.cursor,color:'#000000',dashed:false,locked:false,hidden:false},value:'',existing:false});p.onCancel();return;}const next=[...points,point];const count=['horizontal','ray','text'].includes(p.tool)?1:['channel','long-position','short-position'].includes(p.tool)?3:2;if(next.length===count){if(p.tool==='channel'&&next[0].time===next[1].time)return;p.onDraw({id:crypto.randomUUID(),type:p.tool,points:next,createdAt:p.cursor,color:p.color,dashed:p.dashed,locked:false,hidden:false});setPoints([]);setHover(null);p.onCancel();}else setPoints(next);}
 function renderShape(d:Drawing,draft=false){if(!d.points.length)return null;const isPosition=d.type==='long-position'||d.type==='short-position',entry=d.points[0],rawTarget=d.points[1]||entry,rawStop=d.points[2]||rawTarget,targetPrice=d.type==='long-position'?entry.price+Math.abs(rawTarget.price-entry.price):d.type==='short-position'?entry.price-Math.abs(rawTarget.price-entry.price):rawTarget.price,stopPrice=rawStop.price,effectivePoints=isPosition?[entry,{...rawTarget,price:targetPrice},{...rawStop,price:stopPrice}]:d.points;const a=xy(effectivePoints[0]),b=xy(effectivePoints[1]||effectivePoints[0]),third=xy(effectivePoints[2]||effectivePoints[1]||effectivePoints[0]);const selected=d.id===p.selected;const common={stroke:d.color,strokeWidth:d.lineWidth??(selected?2:1.5),strokeDasharray:d.dashed?'6 5':undefined,fill:'none'};let shape;
 if(d.type==='horizontal')shape=<><line x1={0} x2={(chart.current?.timeScale().width()??size.w-72)} y1={a.y} y2={a.y} {...common}/><text x={12} y={a.y-7} fill={d.color} fontSize={12}>{d.points[0].price.toFixed(2)}</text></>;
 else if(d.type==='ray')shape=<line x1={a.x} x2={(chart.current?.timeScale().width()??size.w-72)} y1={a.y} y2={a.y} {...common}/>;
 else if(d.type==='rect')shape=<rect x={Math.min(a.x,b.x)} y={Math.min(a.y,b.y)} width={Math.abs(b.x-a.x)} height={Math.abs(b.y-a.y)} {...common} fill={d.color} fillOpacity={d.opacity??.08}/>;
 else if(d.type==='text'){const lines=(d.text||'').split('\n');shape=<><rect x={a.x-4} y={a.y-17} width={Math.max(30,...lines.map(line=>line.length*14))+8} height={lines.length*20+4} fill="transparent"/><text x={a.x} y={a.y} fill={d.color} fontSize={14}>{lines.map((line,i)=><tspan key={i} x={a.x} dy={i?20:0}>{line}</tspan>)}</text></>;}
 else if(d.type==='fib'){const options=d.fibOptions??{showPrices:true,showRatios:true,showTrendLine:true};shape=<><rect className="fib-fill" x={Math.min(a.x,b.x)} y={Math.min(a.y,b.y)} width={Math.abs(b.x-a.x)} height={Math.abs(b.y-a.y)} fill={d.color} fillOpacity={d.opacity??.06}/>{fibLevels(d.fibLevels).map((level,i)=>{if(!level.enabled)return null;const price=fibPrice(entry.price,rawTarget.price,level.value),y=xy({time:entry.time,price}).y,color=level.color??d.color;return <g key={i}><line x1={Math.min(a.x,b.x)} x2={Math.max(a.x,b.x)} y1={y} y2={y} {...common} stroke={color}/>{(options.showPrices||options.showRatios)&&<text x={Math.min(a.x,b.x)+5} y={y-5} fill={color} fontSize={12}>{[options.showRatios?String(level.value):'',options.showPrices?price.toFixed(2):''].filter(Boolean).join(' · ')}</text>}</g>;})}{options.showTrendLine&&<line x1={a.x} x2={b.x} y1={a.y} y2={b.y} {...common} strokeDasharray="4 4" opacity={.5}/>}</>;}
 else if(d.type==='channel'){const dy=third.y-(a.y+(b.y-a.y)*(third.x-a.x)/(b.x-a.x||1));shape=<><polygon points={`${a.x},${a.y} ${b.x},${b.y} ${b.x},${b.y+dy} ${a.x},${a.y+dy}`} fill={d.color} fillOpacity={d.opacity??.08}/><line x1={a.x} x2={b.x} y1={a.y} y2={b.y} {...common}/><line x1={a.x} x2={b.x} y1={a.y+dy} y2={b.y+dy} {...common}/><line x1={a.x} x2={b.x} y1={a.y+dy/2} y2={b.y+dy/2} {...common} strokeDasharray="5 5" opacity={.6}/></>;}
 else if(isPosition){const endX=Math.max(a.x+70,b.x,third.x),reward=Math.abs(targetPrice-entry.price),risk=Math.abs(stopPrice-entry.price),ratio=risk?reward/risk:0,isLong=d.type==='long-position',locked=isLong?stopPrice>entry.price:stopPrice<entry.price,breakeven=Math.abs(stopPrice-entry.price)<entry.price*.000001,lockedPercent=Math.abs(stopPrice/entry.price-1)*100,stopColor=locked||breakeven?'#4f8cff':'#f23645',stopFill=locked||breakeven?'#2962ff35':'#f2364542',stopLabel=breakeven?'保本止损':locked?`移动止损 +${lockedPercent.toFixed(2)}%`:'止损',entryMetric=locked?`已锁盈 ${lockedPercent.toFixed(2)}%`:breakeven?'已移至保本':`R:R ${ratio.toFixed(2)}`,greenTop=Math.min(a.y,b.y),greenHeight=Math.abs(a.y-b.y),stopTop=Math.min(a.y,third.y),stopHeight=Math.abs(a.y-third.y);shape=<><rect x={a.x} y={greenTop} width={endX-a.x} height={greenHeight} fill="#08998142" stroke="#089981" strokeWidth={selected?2:1}/><rect x={a.x} y={stopTop} width={endX-a.x} height={stopHeight} fill={stopFill} stroke={stopColor} strokeWidth={selected?2:1}/><line x1={a.x} x2={endX} y1={a.y} y2={a.y} stroke="#e0e3eb" strokeWidth={1.5}/><text x={a.x+7} y={a.y-7} fill="#434651" fontSize={11}>入场 {entry.price.toFixed(2)} · {entryMetric}</text><text x={a.x+7} y={b.y+(b.y<a.y?14:-7)} fill="#089981" fontSize={10}>目标 {targetPrice.toFixed(2)}</text><text x={a.x+7} y={third.y+(third.y<a.y?14:-7)} fill={stopColor} fontSize={10}>{stopLabel} {stopPrice.toFixed(2)}</text></>;}
 else shape=<><line x1={a.x} x2={b.x} y1={a.y} y2={b.y} {...common}/>{d.type==='measure'&&d.points.length>1&&<g><rect x={(a.x+b.x)/2-90} y={(a.y+b.y)/2-31} width={180} height={45} rx={5} fill="#263246"/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-12} textAnchor="middle" fill="#e1e9f2" fontSize={12}>{((d.points[1].price/d.points[0].price-1)*100).toFixed(2)}% · {(d.points[1].price-d.points[0].price).toFixed(2)}</text><text x={(a.x+b.x)/2} y={(a.y+b.y)/2+5} textAnchor="middle" fill="#a4b2c4" fontSize={12}>{Math.abs(Math.round((d.points[1].time-d.points[0].time)/60))} 分钟</text></g>}</>;
 return <g key={d.id} className={d.type==='rect'||d.type==='fib'||isPosition?'drawing-border-only':undefined} onDoubleClick={e=>{if(d.type==='text'&&!d.locked&&!draft){e.stopPropagation();setDrag(null);chart.current?.applyOptions({handleScroll:true,handleScale:true});setTextEditor({drawing:structuredClone(d),value:d.text||'',existing:true});}}} style={{pointerEvents:draft?'none':'visiblePainted',cursor:d.locked?'default':'pointer'}} onPointerDown={e=>{if(p.tool!=='cursor')return;e.stopPropagation();p.onSelect(d.id);const svg=e.currentTarget.ownerSVGElement!;const start=toPoint({...e,currentTarget:svg} as React.PointerEvent<SVGSVGElement>);if(!d.locked&&start){p.onEditStart();setDrag({id:d.id,index:-1,start,original:structuredClone(d)});svg.setPointerCapture(e.pointerId);chart.current?.applyOptions({handleScroll:false,handleScale:false});}}}><g className="drawing-visible">{shape}</g><g className="drawing-hit">{shape}</g>{selected&&!d.locked&&effectivePoints.map((point,i)=>{const v=xy(point);return <circle key={i} cx={v.x} cy={v.y} r={5} fill="#ffffff" stroke={isPosition?(i===1?'#089981':i===2?'#f23645':'#434651'):d.color} strokeWidth={2} style={{pointerEvents:'all',cursor:'move'}} onPointerDown={e=>{e.stopPropagation();p.onEditStart();setDrag({id:d.id,index:i,start:point,original:structuredClone(d)});chart.current?.applyOptions({handleScroll:false,handleScale:false});(e.currentTarget.ownerSVGElement as SVGSVGElement).setPointerCapture(e.pointerId);}}/>;})}</g>;
 }
 const draftPoints=points.length?[...points,...(hover?[hover]:[])]:[];
 return <div className="chart-layer"><div ref={host} className="chart-canvas"/><svg className="drawing-overlay" width={size.w} height={size.h} style={{pointerEvents:p.tool==='cursor'&&!drag?'none':'all',cursor:p.tool==='cursor'?'default':'crosshair'}} onPointerDown={down} onPointerMove={e=>{const pt=toPoint(e);setHover(pt);if(drag&&pt){const d=p.drawings.find(x=>x.id===drag.id);if(d)p.onChange(drag.index===-1?translateDrawing(drag.original,pt.time-drag.start.time,pt.price-drag.start.price):{...d,points:d.points.map((x,i)=>i===drag.index?pt:x)});}}} onPointerUp={()=>{setDrag(null);chart.current?.applyOptions({handleScroll:p.tool==='cursor',handleScale:p.tool==='cursor'});}} onPointerCancel={()=>{setDrag(null);chart.current?.applyOptions({handleScroll:p.tool==='cursor',handleScale:p.tool==='cursor'});}}><defs><clipPath id="plot-clip"><rect width={Math.max(0,(chart.current?.timeScale().width()??size.w-72))} height={Math.max(0,size.h-28)}/></clipPath></defs><g clipPath="url(#plot-clip)">{p.drawings.filter(d=>!d.hidden&&d.createdAt<=p.cursor).map(d=>renderShape(d))}{draftPoints.length>0&&renderShape({id:'draft',type:p.tool as Drawing['type'],points:draftPoints,createdAt:p.cursor,color:p.color,dashed:true,locked:false,hidden:false,text:p.text},true)}</g></svg>{textEditor&&<div className="chart-text-editor" style={{left:Math.max(8,Math.min(xy(textEditor.drawing.points[0]).x,size.w-260)),top:Math.max(8,Math.min(xy(textEditor.drawing.points[0]).y-18,size.h-130))}}><textarea autoFocus aria-label="图表文字" placeholder="输入文字" maxLength={200} value={textEditor.value} style={{color:textEditor.drawing.color}} onChange={e=>setTextEditor({...textEditor,value:e.target.value})} onKeyDown={e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();setTextEditor(null);}else if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();commitText();}}}/><div><span>Enter 确认 · Shift+Enter 换行</span><button onClick={()=>setTextEditor(null)}>取消</button><button disabled={!textEditor.value.trim()} onClick={commitText}>确定</button></div></div>}{p.tool!=='cursor'&&<div className="drawing-hint">{p.tool==='pick'?'点击图表设置回放起点':`${({fib:'斐波那契回撤',horizontal:'水平线',ray:'水平射线',trend:'趋势线',channel:'平行通道',rect:'矩形',text:'文字',measure:'测量','long-position':'多头仓位','short-position':'空头仓位'} as Record<string,string>)[p.tool]} · 点击第 ${points.length+1} 个点`}<span>Esc 取消</span></div>}</div>;
}
