"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Slider} from '@/components/ui/slider';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle,AlertDialogTrigger} from '@/components/ui/alert-dialog';
import {Play,Pause,CandlestickChart,MousePointer2,Minus,TrendingUp,TrendingDown,Square,Layers,Save,SlidersHorizontal,SkipBack,SkipForward,RotateCcw,Undo2,Redo2,Type,ArrowRight,Magnet,PanelRightClose,PanelRightOpen,CalendarDays,Crosshair,Trash2,Check,LoaderCircle,BookOpen,Plus,HelpCircle,ChevronRight,ReceiptText,Link2,RefreshCw,ShieldCheck,Shuffle,ListFilter,LockKeyhole,UnlockKeyhole,Eye,EyeOff,Settings2} from 'lucide-react';
import FibStyleSettings from '@/components/fib-style-settings';
import ReplayChart,{type Tool} from '@/components/replay-chart';
import {prefetchLeadSeconds,contiguousDays} from '@/lib/replay-buffer';
import {aggregate,PERIODS,INSTRUMENTS,fmtTime,type Candle} from '@/lib/replay';
import type {Drawing,Session} from '@/lib/session-schema';
import type {TradeFill} from '@/lib/okx';
type DrawingIconProps=React.SVGProps<SVGSVGElement>;
function DrawingIcon({children,...props}:DrawingIconProps){return <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}>{children}</svg>}
function TrendToolIcon(props:DrawingIconProps){return <DrawingIcon {...props}><path d="M5 19L19 5"/><circle cx="4" cy="20" r="2" fill="var(--background)"/><circle cx="20" cy="4" r="2" fill="var(--background)"/></DrawingIcon>}
function HorizontalToolIcon(props:DrawingIconProps){return <DrawingIcon {...props}><path d="M2 12h8m4 0h8"/><circle cx="12" cy="12" r="2" fill="var(--background)"/></DrawingIcon>}
function RayToolIcon(props:DrawingIconProps){return <DrawingIcon {...props}><path d="M6 12h16"/><circle cx="4" cy="12" r="2" fill="var(--background)"/></DrawingIcon>}
function ChannelToolIcon(props:DrawingIconProps){return <DrawingIcon {...props}><path d="M5 16L17 4M9 22L21 10"/><circle cx="4" cy="17" r="2" fill="var(--background)"/><circle cx="18" cy="3" r="2" fill="var(--background)"/><circle cx="16" cy="15" r="2" fill="var(--background)"/></DrawingIcon>}
function PositionToolIcon({short=false,...props}:DrawingIconProps&{short?:boolean}){return <DrawingIcon {...props}><path d="M5 4h17M2 17h20M5 22h17"/><circle cx="3" cy="4" r="2" fill="var(--background)"/><circle cx="3" cy="22" r="2" fill="var(--background)"/>{short?<path d="M14 8h-3a2 2 0 0 0 0 4h1a2 2 0 0 1 0 4H9"/>:<path d="M10 8v6h4"/>}</DrawingIcon>}
function LongToolIcon(props:DrawingIconProps){return <PositionToolIcon {...props}/>}
function ShortToolIcon(props:DrawingIconProps){return <PositionToolIcon {...props} short/>}
const toolsList=[{key:'cursor',label:'选择 / 拖动',icon:MousePointer2},{key:'long-position',label:'多头仓位',icon:LongToolIcon},{key:'short-position',label:'空头仓位',icon:ShortToolIcon},{key:'horizontal',label:'水平线',icon:HorizontalToolIcon},{key:'ray',label:'水平射线',icon:RayToolIcon},{key:'trend',label:'趋势线',icon:TrendToolIcon},{key:'channel',label:'平行通道',icon:ChannelToolIcon},{key:'fib',label:'斐波那契回撤',icon:ListFilter},{key:'rect',label:'矩形',icon:Square},{key:'text',label:'文字',icon:Type}] as const;
const yesterday=()=>new Date(Date.now()-86400000).toISOString().slice(0,10);
const HISTORY_DAYS=30;
const randomDay=()=>{const start=Date.parse('2021-01-31T00:00:00Z'),finish=Date.parse(yesterday()+'T00:00:00Z'),time=start+Math.floor(Math.random()*Math.max(1,finish-start));return new Date(time).toISOString().slice(0,10);};
function Choice({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
function IconButton({label,children,...p}:React.ComponentProps<typeof Button>&{label:string}){return <Button variant="ghost" size="icon" title={label} aria-label={label} {...p}>{children}</Button>}
export default function Home(){
 const [instrument,setInstrument]=useState('BTC-USDT'),[endDay,setEndDay]=useState(''),[days,setDays]=useState<number>(HISTORY_DAYS),[data,setData]=useState<Candle[]>([]),[overview,setOverview]=useState<Candle[]>([]),[cursor,setCursor]=useState(0),[period,setPeriod]=useState(15),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[stepMode,setStepMode]=useState('period'),[loading,setLoading]=useState(true),[progress,setProgress]=useState('正在抽取随机行情'),[error,setError]=useState(''),[missing,setMissing]=useState(0),[fetchedAt,setFetchedAt]=useState('');
 const [tool,setTool]=useState<Tool>('cursor'),[drawings,setDrawings]=useState<Drawing[]>([]),[selected,setSelected]=useState<string|null>(null),[color,setColor]=useState('#2962ff'),[dashed,setDashed]=useState(false),[snap,setSnap]=useState(false),[text,setText]=useState('关键位置'),[ma,setMa]=useState(true),[ema,setEma]=useState(false),[hover,setHover]=useState<Candle|null>(null);
 const [notes,setNotes]=useState<Session['notes']>([]),[note,setNote]=useState(''),[side,setSide]=useState(false),[sideTab,setSideTab]=useState('objects'),[dateOpen,setDateOpen]=useState(false),[dateValue,setDateValue]=useState(''),[rangeDays,setRangeDays]=useState(String(HISTORY_DAYS)),[jumpValue,setJumpValue]=useState(''),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[savedAt,setSavedAt]=useState('');
 const [okxStatus,setOkxStatus]=useState<{connected:boolean;keyHint?:string;label?:string}>({connected:false}),[connectionOpen,setConnectionOpen]=useState(false),[apiKey,setApiKey]=useState(''),[secretKey,setSecretKey]=useState(''),[passphrase,setPassphrase]=useState(''),[demo,setDemo]=useState(false),[connecting,setConnecting]=useState(false),[fills,setFills]=useState<TradeFill[]>([]),[syncingFills,setSyncingFills]=useState(false),[fillsMessage,setFillsMessage]=useState(''),[showFills,setShowFills]=useState(true);
 const [cacheStatus,setCacheStatus]=useState<{days:number;candles:number;allDailyCached:boolean}>({days:0,candles:0,allDailyCached:false});
 const undoStack=useRef<Drawing[][]>([]),redoStack=useRef<Drawing[][]>([]),[,historyTick]=useState(0),controller=useRef<AbortController|null>(null),extending=useRef(false),retryAfter=useRef(0),live=useRef({} as {cursor:number;data:Candle[];period:number;loading:boolean;stepMode:string});live.current={cursor,data,period,loading,stepMode};
 const bars=useMemo(()=>period===1440&&overview.length?overview.filter(candle=>candle.time+86400<=cursor):aggregate(data,period,cursor),[data,overview,period,cursor]),last=bars.at(-1),display=hover||last,visibleDrawings=drawings.filter(d=>d.createdAt<=cursor),visibleFills=fills.filter(fill=>fill.time<=cursor),currentIndex=Math.max(0,data.findIndex(x=>x.time+60>=cursor)),first=data[0]?.time||0,end=(data.at(-1)?.time||0)+60;
 const step=stepMode==='minute'?60:period*60;
 async function load(inst:string,day:string,count:number,restore?:Session){
  controller.current?.abort();extending.current=false;retryAfter.current=0;const ac=new AbortController();controller.current=ac;setLoading(true);setPlaying(false);setError('');setHover(null);setTool('cursor');setSelected(null);setData([]);setOverview([]);setInstrument(inst);setEndDay(day);setDays(count);setMissing(0);setSavedAt('');setDirty(false);void fetch(`/api/history?instrument=${encodeURIComponent(inst)}`,{signal:ac.signal}).then(async response=>{const result=await response.json() as {candles?:Candle[]};if(response.ok&&!ac.signal.aborted)setOverview(result.candles||[]);}).catch(()=>{});
  const dates=Array.from({length:count},(_,i)=>new Date(Date.parse(day+'T00:00:00Z')-(count-1-i)*86400000).toISOString().slice(0,10));let all:Candle[]=[],holes=0,stamp='',completed=0,next=0;const failed:string[]=[];
  try{
   const fetchDay=async(d:string)=>{for(let attempt=0;attempt<2;attempt++){try{const res=await fetch(`/api/candles?instrument=${encodeURIComponent(inst)}&day=${d}`,{signal:ac.signal});const j=await res.json() as {error?:string;candles:Candle[];missing:number;fetchedAt:string};if(!res.ok)throw new Error(j.error||'行情读取失败');all.push(...j.candles);holes+=j.missing;stamp=j.fetchedAt;completed++;const snapshot=[...new Map(all.map(x=>[x.time,x])).values()].sort((a,b)=>a.time-b.time);setProgress(`并行读取真实行情 ${completed} / ${count} 天`);setData(snapshot);setMissing(holes);setFetchedAt(stamp);if(!restore&&snapshot.length)setCursor(snapshot[Math.floor(snapshot.length*.7)].time+60);return;}catch(error){if(ac.signal.aborted)throw error;if(attempt===1){failed.push(d);completed++;setProgress(`已读取 ${completed} / ${count} 天 · ${failed.length} 天待跳过`);}else await new Promise(resolve=>setTimeout(resolve,400));}}};
   const worker=async()=>{while(!ac.signal.aborted){const index=next++;if(index>=dates.length)return;await fetchDay(dates[index]);}};await Promise.all(Array.from({length:Math.min(4,count)},worker));
   if(ac.signal.aborted)return;all=[...new Map(all.map(x=>[x.time,x])).values()].sort((a,b)=>a.time-b.time);if(!all.length)throw new Error('历史行情暂时无法读取，请重试');setData(all);setMissing(holes);setFetchedAt(stamp);const max=all.at(-1)!.time+60,min=all[0].time+60;setCursor(restore?Math.max(min,Math.min(max,restore.cursor)):all[Math.floor(all.length*.7)].time+60);setDrawings(restore?.drawings||[]);setNotes(restore?.notes||[]);setPeriod(restore?.period||15);setMa(restore?.ma??true);setEma(restore?.ema??false);undoStack.current=[];redoStack.current=[];historyTick(v=>v+1);if(failed.length)setMessage(`已加载可用行情，${failed.length} 天暂时缺失，可稍后重新随机`);else if(restore)setMessage('已恢复上次保存的复盘');
  }catch(e){if(!ac.signal.aborted)setError(e instanceof Error?e.message:'读取失败，请重试');}finally{if(!ac.signal.aborted)setLoading(false);}
 }
 async function extendForward(){
  const ac=controller.current;if(!ac||ac.signal.aborted||extending.current||loading||!data.length||Date.now()<retryAfter.current)return;
  const lastDayStart=Math.floor(data.at(-1)!.time/86400)*86400,nextDayStart=lastDayStart+86400,latestDayStart=Date.parse(yesterday()+'T00:00:00Z')/1000;if(nextDayStart>latestDayStart)return;
  extending.current=true;const inst=instrument,count=Math.min(HISTORY_DAYS,Math.floor((latestDayStart-nextDayStart)/86400)+1),dates=Array.from({length:count},(_,i)=>new Date((nextDayStart+i*86400)*1000).toISOString().slice(0,10));const results=new Map<string,{candles:Candle[];missing:number;fetchedAt:string}>();let next=0;
  try{
   const fetchDay=async(day:string)=>{for(let attempt=0;attempt<3;attempt++){try{const response=await fetch(`/api/candles?instrument=${encodeURIComponent(inst)}&day=${day}`,{signal:ac.signal});const result=await response.json() as {error?:string;candles:Candle[];missing:number;fetchedAt:string};if(!response.ok||!result.candles?.length)throw new Error(result.error||'后续行情暂不可用');results.set(day,result);return;}catch(error){if(ac.signal.aborted)throw error;if(attempt<2)await new Promise(resolve=>setTimeout(resolve,500*(attempt+1)));}}};
   const worker=async()=>{while(!ac.signal.aborted){const index=next++;if(index>=dates.length)return;await fetchDay(dates[index]);}};await Promise.all(Array.from({length:Math.min(4,count)},worker));
   if(ac.signal.aborted||controller.current!==ac)return;
   // Only append consecutive successful days. Never jump over a failed fetch.
   const ready=contiguousDays(dates,results),added=ready.flatMap(day=>results.get(day)!.candles);
   if(added.length){setData(current=>[...new Map([...current,...added].map(item=>[item.time,item])).values()].sort((a,b)=>a.time-b.time));setEndDay(ready.at(-1)!);setDays(value=>Math.min(3650,value+ready.length));setMissing(value=>value+ready.reduce((sum,day)=>sum+results.get(day)!.missing,0));setFetchedAt(results.get(ready.at(-1)!)!.fetchedAt);}
   if(ready.length<count)retryAfter.current=Date.now()+30000;
  }catch{if(!ac.signal.aborted)retryAfter.current=Date.now()+30000;}finally{if(controller.current===ac)extending.current=false;}
 }
 useEffect(()=>{let cancelled=false;(async()=>{let saved:Session|undefined;try{const r=await fetch('/api/session?instrument=BTC-USDT');if(!r.ok)throw new Error();const j=await r.json() as {session:Session|null};saved=j.session||undefined;}catch{setMessage('暂时无法恢复已保存进度，可继续开始随机行情');}if(!cancelled){const day=saved?.endDay||randomDay();setDateValue(day);await load('BTC-USDT',day,HISTORY_DAYS,saved);}})();return()=>{cancelled=true;controller.current?.abort();};},[]);
 useEffect(()=>{let cancelled=false;(async()=>{try{const response=await fetch('/api/okx/connection');const result=await response.json() as {connected?:boolean;keyHint?:string;label?:string};if(!cancelled&&response.ok)setOkxStatus({connected:Boolean(result.connected),keyHint:result.keyHint,label:result.label});}catch{}})();return()=>{cancelled=true};},[]);
 useEffect(()=>{const timer=setTimeout(()=>{void (async()=>{for(const item of INSTRUMENTS){try{await fetch(`/api/history?instrument=${encodeURIComponent(item)}`);}catch{}}})();},1500);return()=>clearTimeout(timer);},[]);
 useEffect(()=>{if(loading)return;let cancelled=false;(async()=>{try{const response=await fetch(`/api/cache/status?instrument=${encodeURIComponent(instrument)}`);const result=await response.json() as {days?:number;candles?:number;allDailyCached?:boolean};if(!cancelled&&response.ok)setCacheStatus({days:result.days||0,candles:result.candles||0,allDailyCached:Boolean(result.allDailyCached)});}catch{}})();return()=>{cancelled=true};},[instrument,loading]);
 useEffect(()=>{if(okxStatus.connected&&first&&end)void syncFills(true);else if(!okxStatus.connected)setFills([]);},[okxStatus.connected,instrument,first,end]);
 useEffect(()=>{
  const prefetch=()=>{if(!data.length||loading||extending.current)return;const latestEnd=Date.parse(yesterday()+'T00:00:00Z')/1000+86400;if(end<latestEnd&&cursor>=end-prefetchLeadSeconds(period))void extendForward();};
  prefetch();const timer=setInterval(prefetch,10000);return()=>clearInterval(timer);
 },[cursor,end,period,loading,data.length,instrument]);
 useEffect(()=>{if(!playing||loading)return;const timer=setInterval(()=>{setCursor(value=>{const s=live.current,maximum=(s.data.at(-1)?.time||0)+60;const next=Math.min(maximum,value+(s.stepMode==='minute'?60:s.period*60));if(next>=maximum)setPlaying(false);return next;});setDirty(true);},1000/speed);return()=>clearInterval(timer);},[playing,speed,loading]);
 useEffect(()=>{const handle=(e:KeyboardEvent)=>{const tag=(e.target as HTMLElement)?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag)||(e.target as HTMLElement)?.isContentEditable)return;const deleteKey=e.key==='Delete'||e.key==='Backspace'||e.code==='Delete'||e.code==='Backspace';if(deleteKey&&selected){e.preventDefault();e.stopPropagation();deleteDrawing(selected);}else if(e.key==='Escape'){setTool('cursor');setSelected(null);}else if(e.code==='Space'){e.preventDefault();if(!live.current.loading&&live.current.data.length)setPlaying(v=>!v);}else if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const s=live.current;if(s.data.length){setPlaying(false);setCursor(v=>Math.max(s.data[0].time+60,Math.min(s.data.at(-1)!.time+60,v+(e.key==='ArrowRight'?1:-1)*(s.stepMode==='minute'?60:s.period*60))));setDirty(true);}}};window.addEventListener('keydown',handle,true);return()=>window.removeEventListener('keydown',handle,true);},[selected,drawings]);
 useEffect(()=>{const handler=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[dirty]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),6000);return()=>clearTimeout(t);},[message]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!ctx)return;const ac=new AbortController();try{ctx.registerTool({name:'advance_replay_minutes',description:'将当前历史回放向前推进指定分钟数，暂停自动播放。',inputSchema:{type:'object',properties:{minutes:{type:'integer',minimum:1,maximum:1440}},required:['minutes'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const m=(input as {minutes?:number})?.minutes;if(typeof m!=='number'||!Number.isInteger(m)||m<1||m>1440)throw new Error('minutes 必须为 1 到 1440 的整数');const s=live.current;if(s.loading||!s.data.length)throw new Error('行情尚未就绪');const next=Math.min(s.data.at(-1)!.time+60,s.cursor+m*60);setPlaying(false);setCursor(next);setDirty(true);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return{cursor:next,time:fmtTime(next)};}},{signal:ac.signal});}catch{}return()=>ac.abort();},[]);
 function record(){undoStack.current.push(structuredClone(drawings));if(undoStack.current.length>50)undoStack.current.shift();redoStack.current=[];historyTick(v=>v+1);}
 function edit(next:Drawing[]){record();setDrawings(next);setDirty(true);}
 function deleteDrawing(id:string){record();setDrawings(list=>list.filter(item=>item.id!==id));setSelected(current=>current===id?null:current);setDirty(true);setMessage('绘图已删除，可点击撤销恢复');}
 function undo(){const next=undoStack.current.pop();if(next){redoStack.current.push(structuredClone(drawings));setDrawings(next);setDirty(true);historyTick(v=>v+1);}}
 function redo(){const next=redoStack.current.pop();if(next){undoStack.current.push(structuredClone(drawings));setDrawings(next);setDirty(true);historyTick(v=>v+1);}}
 function move(delta:number){setPlaying(false);setHover(null);setCursor(v=>Math.max(first+60,Math.min(end,v+delta)));setDirty(true);}
 async function save(){if(!data.length)return false;setSaving(true);try{const session:Session={instrument,endDay,days,cursor,period,drawings,notes,ma,ema};const res=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(session)});const j=await res.json() as {error?:string;updatedAt:number};if(!res.ok)throw new Error(j.error);setDirty(false);setSavedAt(new Date(j.updatedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}));setMessage('复盘已保存，包含进度、画线和笔记');return true;}catch(e){setMessage(e instanceof Error?e.message:'保存失败，请重试');return false;}finally{setSaving(false);}}
 async function changeInstrument(inst:string){if(dirty&&!(await save()))return;let saved:Session|undefined;try{const r=await fetch('/api/session?instrument='+inst);if(!r.ok)throw new Error();saved=(await r.json() as {session:Session|null}).session||undefined;}catch{setMessage('无法读取该品种的保存进度，请稍后重试');return;}await load(inst,saved?.endDay||endDay,HISTORY_DAYS,saved);}
 async function randomize(){setPlaying(false);setTool('cursor');setSelected(null);if(dirty&&!(await save()))return;const inst=INSTRUMENTS[Math.floor(Math.random()*INSTRUMENTS.length)],day=randomDay();setDateValue(day);setDrawings([]);setNotes([]);setFills([]);await load(inst,day,HISTORY_DAYS);setMessage('已抽取一段随机真实行情，未来走势保持隐藏');}
 async function connectOkx(){setConnecting(true);setFillsMessage('');try{const response=await fetch('/api/okx/connection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey,secretKey,passphrase,demo})});const result=await response.json() as {error?:string;connected?:boolean;keyHint?:string;label?:string};if(!response.ok)throw new Error(result.error||'连接失败');setOkxStatus({connected:true,keyHint:result.keyHint,label:result.label});setApiKey('');setSecretKey('');setPassphrase('');setConnectionOpen(false);setSide(true);setSideTab('fills');setMessage('OKX 只读账户已连接，正在同步交割单');}catch(error){setFillsMessage(error instanceof Error?error.message:'连接失败');}finally{setConnecting(false);}}
 async function disconnectOkx(){try{const response=await fetch('/api/okx/connection',{method:'DELETE'});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'断开失败');setOkxStatus({connected:false});setFills([]);setFillsMessage('');setMessage('已断开 OKX，保存的密钥已删除');}catch(error){setMessage(error instanceof Error?error.message:'断开失败');}}
 async function syncFills(silent=false){if(!first||!end||syncingFills)return;setSyncingFills(true);if(!silent)setFillsMessage('正在从 OKX 读取交割明细…');try{const begin=Math.max(first,end-31*86400);const response=await fetch(`/api/okx/fills?instrument=${encodeURIComponent(instrument)}&begin=${begin*1000}&end=${end*1000}`);const result=await response.json() as {error?:string;fills?:TradeFill[];limited?:boolean;message?:string};if(!response.ok)throw new Error(result.error||'同步失败');setFills(result.fills||[]);setFillsMessage(result.message||`${(result.fills||[]).length} 笔交割明细已同步${result.limited?' · 受最近 3 个月范围限制':''}`);}catch(error){setFillsMessage(error instanceof Error?error.message:'同步失败');}finally{setSyncingFills(false);}}
 function selectTool(t:Tool){setTool(t);setSelected(null);setPlaying(false);}
 const activeDrawing=drawings.find(d=>d.id===selected&&d.createdAt<=cursor);
 function updateDrawing(patch:Partial<Drawing>){if(activeDrawing)edit(drawings.map(d=>d.id===activeDrawing.id?{...d,...patch}:d));}
 const price=(v?:number)=>v?.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})||'—';
 return <main className="workspace">
 <div className="marketbar"><div className="brand"><CandlestickChart/><strong>逐刻</strong></div><div className={'coin '+(instrument.startsWith('ETH')?'eth':'')}>{instrument.startsWith('BTC')?'₿':instrument.startsWith('ETH')?'Ξ':'◎'}</div><div className="instrument-select"><Choice label="交易品种" value={instrument} onChange={changeInstrument} items={INSTRUMENTS.map(x=>({value:x,label:x.replace('-USDT-SWAP',' / USDT 永续').replace('-USDT',' / USDT')}))}/></div><a className="chart-attribution" href="https://www.tradingview.com/" target="_blank" rel="noreferrer" title="TradingView Lightweight Charts™ · Copyright (с) 2025 TradingView, Inc.">TradingView Lightweight Charts™</a><div className="periods">{PERIODS.map(x=><Button variant="ghost" className={period===x.value?'active':''} onClick={()=>{setPlaying(false);setHover(null);setPeriod(x.value);setDirty(true);}} key={x.value}>{x.label}</Button>)}</div><Dialog><DialogTrigger asChild><Button variant="ghost" className="indicator-btn"><SlidersHorizontal/>指标</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>技术指标</DialogTitle><DialogDescription>只使用当前回放时刻之前的行情计算。</DialogDescription></DialogHeader><Button variant={ma?'secondary':'outline'} onClick={()=>{setMa(v=>!v);setDirty(true);}}>{ma&&<Check/>}MA 20 · 简单移动平均</Button><Button variant={ema?'secondary':'outline'} onClick={()=>{setEma(v=>!v);setDirty(true);}}>{ema&&<Check/>}EMA 50 · 指数移动平均</Button><p className="muted">数据不足 20 / 50 根时，对应均线暂不显示。</p></DialogContent></Dialog><Button variant="outline" className="random-market" onClick={randomize} disabled={loading}><Shuffle/>{loading?'加载中':'随机行情'}</Button></div>
 <section className="desk"><aside className="tools">{toolsList.map(x=><IconButton label={x.label} key={x.key} className={tool===x.key?'active':''} onClick={()=>selectTool(x.key)} disabled={!data.length||loading}><x.icon/></IconButton>)}<div className="tool-divider"/><IconButton label="吸附到开高低收" className={snap?'active':''} onClick={()=>setSnap(v=>!v)}><Magnet/></IconButton><label className="color-picker" title="画线颜色"><input aria-label="画线颜色" type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><IconButton label="撤销画图" disabled={!undoStack.current.length} onClick={undo}><Undo2/></IconButton><IconButton label="重做画图" disabled={!redoStack.current.length} onClick={redo}><Redo2/></IconButton></aside>
 <section className="chart-shell"><div className="chart-title">{instrument.startsWith('BTC')?'比特币':instrument.startsWith('ETH')?'以太坊':'Solana'} / 泰达币 <span>{PERIODS.find(x=>x.value===period)?.label} · OKX</span><div className="ohlc"><span>开 <b>{price(display?.open)}</b></span><span>高 <b>{price(display?.high)}</b></span><span>低 <b>{price(display?.low)}</b></span><span>收 <b className={display&&display.close>=display.open?'up':'down'}>{price(display?.close)}</b></span></div><div className="legend">{ma&&<span className="ma">— MA 20</span>}{ema&&<span className="ema">— EMA 50</span>}<span>VOL · {instrument.endsWith('SWAP')?'张':instrument.split('-')[0]}</span></div></div>
 <ReplayChart candles={bars} period={period} cursor={cursor} drawings={drawings} fills={fills} showFills={showFills} tool={tool} color={color} dashed={dashed} snap={snap} ma={ma} ema={ema} selected={selected} onSelect={setSelected} onDraw={d=>{if(drawings.length>=200){setMessage('单次复盘最多保留 200 个绘图');return;}edit([...drawings,d]);setSelected(d.id);}} onChange={d=>{setDrawings(list=>list.map(x=>x.id===d.id?d:x));setDirty(true);}} onEditStart={record} onCancel={()=>setTool('cursor')} onPick={t=>{setCursor(Math.max(first+60,t));setDirty(true);}} resetKey={instrument+first} onHover={setHover} text={text}/>
 {(error||(loading&&!data.length))&&<div className="chart-empty"><CandlestickChart size={42}/><h2>{error?'暂时无法加载行情':'正在准备第一批行情'}</h2><p role="status">{error||progress}</p>{loading?<LoaderCircle className="spin"/>:<Button onClick={()=>load(instrument,endDay,days)}>重新加载</Button>}<span>OKX 官方行情 · 不使用模拟价格</span></div>}
 </section>
 <Dialog open={side} onOpenChange={setSide}><DialogContent className="chart-manager"><DialogHeader><DialogTitle>复盘工具</DialogTitle><DialogDescription>管理绘图、笔记和成交信息。</DialogDescription></DialogHeader><div className="panel-tabs"><Button variant="ghost" className={sideTab==='notes'?'tab-active':''} onClick={()=>setSideTab('notes')}><BookOpen/>笔记</Button><Button variant="ghost" className={sideTab==='objects'?'tab-active':''} onClick={()=>setSideTab('objects')}><Layers/>绘图 {visibleDrawings.length}</Button><Button variant="ghost" className={sideTab==='fills'?'tab-active':''} onClick={()=>setSideTab('fills')}><ReceiptText/>交割 {visibleFills.length}</Button></div> {sideTab==='objects'&&<div className="panel-section object-section"><div className="section-label"><span>绘图对象</span><span className="muted">{visibleDrawings.length} 个</span></div>{visibleDrawings.map(d=><div className={'object-row '+(d.id===selected?'selected':'')} key={d.id}><button className="object-name" onClick={()=>setSelected(d.id)}><span style={{background:d.color}}/>{toolsList.find(t=>t.key===d.type)?.label||d.type}</button><IconButton label={d.hidden?'显示绘图':'隐藏绘图'} onClick={()=>edit(drawings.map(x=>x.id===d.id?{...x,hidden:!x.hidden}:x))}>{d.hidden?<EyeOff/>:<Eye/>}</IconButton><IconButton label={d.locked?'解锁绘图':'锁定绘图'} onClick={()=>edit(drawings.map(x=>x.id===d.id?{...x,locked:!x.locked}:x))}>{d.locked?<LockKeyhole/>:<UnlockKeyhole/>}</IconButton><IconButton label="删除绘图" onClick={()=>deleteDrawing(d.id)}><Trash2/></IconButton></div>)}{!visibleDrawings.length&&<div className="empty-notes"><Layers/><p>在图表上标记你的判断</p><span>选择左侧工具开始绘图</span></div>}{activeDrawing&&<div className="object-edit"><strong>坐标与样式</strong>{activeDrawing.type==='fib'&&<FibStyleSettings key={activeDrawing.id} drawing={activeDrawing} onApply={patch=>{updateDrawing(patch);setSide(false);}}/>}{activeDrawing.type==='text'&&<label>文字<Input aria-label="绘图文字" value={activeDrawing.text||''} maxLength={200} onChange={e=>updateDrawing({text:e.target.value})}/></label>}{activeDrawing.points.map((point,i)=><fieldset key={i} disabled={activeDrawing.locked}><legend>锚点 {i+1}</legend><label>价格<Input aria-label={`锚点 ${i+1} 价格`} type="number" step="any" min="0.00000001" value={point.price} onChange={e=>{const price=Number(e.target.value);if(price>0)updateDrawing({points:activeDrawing.points.map((p,j)=>j===i?{...p,price}:p)});}}/></label><label>时间<Input aria-label={`锚点 ${i+1} 时间`} type="datetime-local" step="1" value={new Date(point.time*1000+28800000).toISOString().slice(0,19)} onChange={e=>{const time=Date.parse(e.target.value+'+08:00')/1000;if(Number.isFinite(time)&&time>=0)updateDrawing({points:activeDrawing.points.map((p,j)=>j===i?{...p,time}:p)});}}/></label></fieldset>)}<small>时间为北京时间，切换周期不会改写锚点。</small></div>}</div>}
 {sideTab==='notes'&&<div className="panel-section notes-section"><div className="section-label"><span>记录此刻的判断</span><span className="muted">{notes.filter(n=>n.time<=cursor).length} 条</span></div><Textarea aria-label="复盘笔记" placeholder="为什么在这里画线？接下来观察什么？" value={note} onChange={e=>setNote(e.target.value)} maxLength={3000} rows={4}/><Button variant="outline" className="add-note" disabled={!note.trim()||!data.length||notes.length>=100} onClick={()=>{setNotes(n=>[...n,{id:crypto.randomUUID(),time:cursor,text:note.trim()}]);setNote('');setDirty(true);}}><Plus/>添加笔记</Button><div className="notes-list">{notes.filter(n=>n.time<=cursor).slice().reverse().map(n=><article className="note-item" key={n.id}><span>{fmtTime(n.time)}</span><p>{n.text}</p><IconButton label="删除笔记" onClick={()=>{setNotes(ns=>ns.filter(x=>x.id!==n.id));setDirty(true);}}><Trash2/></IconButton></article>)}{!notes.filter(n=>n.time<=cursor).length&&<div className="empty-notes"><BookOpen/><p>每次判断，都值得记录</p><span>笔记会关联当前回放时间</span></div>}</div></div>}
 {sideTab==='fills'&&<div className="panel-section fills-section">{okxStatus.connected?<><div className="connection-summary"><span className="connected-dot"/><div><strong>{okxStatus.label||'OKX 只读账户'}</strong><small>{okxStatus.keyHint} · 仅读取</small></div><Button variant="outline" size="sm" onClick={()=>syncFills(false)} disabled={syncingFills}>{syncingFills?<LoaderCircle className="spin"/>:<RefreshCw/>}同步</Button></div><div className="fills-toolbar"><label><input type="checkbox" checked={showFills} onChange={event=>setShowFills(event.target.checked)}/>在图表显示买卖标记</label><span>{visibleFills.length} / {fills.length} 笔</span></div>{fillsMessage&&<p className="fills-message">{fillsMessage}</p>}<div className="fills-list">{visibleFills.slice().reverse().map(fill=><article className="fill-item" key={fill.id}><div><span className={fill.side==='buy'?'fill-side buy':'fill-side sell'}>{fill.side==='buy'?'买入':'卖出'}</span><strong>{price(fill.price)}</strong></div><p>{fill.size.toLocaleString('en-US',{maximumSignificantDigits:8})} {instrument.endsWith('-SWAP')?'张':instrument.split('-')[0]} · {fill.liquidity==='maker'?'Maker':fill.liquidity==='taker'?'Taker':'成交'}</p><small>{fmtTime(fill.time)}{fill.pnl?` · 已实现盈亏 ${fill.pnl}`:''}{fill.fee?` · 手续费 ${fill.fee} ${fill.feeCurrency}`:''}</small></article>)}{!visibleFills.length&&!syncingFills&&<div className="empty-notes"><ReceiptText/><p>当前回放时间前没有交割记录</p><span>向前推进回放，成交标记会按时间出现</span></div>}</div><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" className="disconnect-button">断开 OKX 连接</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>断开 OKX 只读连接？</AlertDialogTitle><AlertDialogDescription>服务器中加密保存的 API Key、Secret Key 和 Passphrase 将被永久删除。你的复盘、画线和笔记不受影响。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={disconnectOkx}>确认断开并删除密钥</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>:<div className="empty-connection"><ShieldCheck/><h3>连接只读 OKX 账户</h3><p>读取最近 3 个月的成交明细，在 K 线上显示真实买入和卖出位置。</p><Button onClick={()=>setConnectionOpen(true)}><Link2/>连接 OKX</Button><small>只接受“读取”权限。含交易或提现权限的密钥会被拒绝。</small></div>}</div>}
 </DialogContent></Dialog>
 </section>
{message&&<div className="toast" role="status">{message}</div>}
 {activeDrawing&&<div className="floating-drawing-toolbar" aria-label="绘图编辑工具栏"><span>{toolsList.find(t=>t.key===activeDrawing.type)?.label}</span><input aria-label="选中绘图颜色" type="color" value={activeDrawing.color} onChange={e=>updateDrawing({color:e.target.value})}/><select aria-label="绘图线宽" value={activeDrawing.lineWidth??2} onChange={e=>updateDrawing({lineWidth:Number(e.target.value)})}>{[1,2,3,4].map(n=><option value={n} key={n}>{n}px</option>)}</select><IconButton label="切换虚线" className={activeDrawing.dashed?'active':''} onClick={()=>updateDrawing({dashed:!activeDrawing.dashed})}><Minus/></IconButton><label title="填充透明度"><input aria-label="填充透明度" type="range" min="0" max=".5" step=".01" value={activeDrawing.opacity??.08} onChange={e=>updateDrawing({opacity:Number(e.target.value)})}/></label><IconButton label={activeDrawing.type==='fib'?'斐波那契样式与比例':'绘图坐标设置'} onClick={()=>{setSide(true);setSideTab('objects');}}><Settings2/></IconButton><IconButton label={activeDrawing.locked?'解锁绘图':'锁定绘图'} onClick={()=>updateDrawing({locked:!activeDrawing.locked})}>{activeDrawing.locked?<LockKeyhole/>:<UnlockKeyhole/>}</IconButton><IconButton label="删除选中绘图" onClick={()=>deleteDrawing(activeDrawing.id)}><Trash2/></IconButton></div>}{overview.length>0&&<div className="history-depth">完整日线 · {overview.length.toLocaleString()} 根 · 缓存 {cacheStatus.days} 天分钟线</div>}{loading&&data.length>0&&<div className="load-progress"><LoaderCircle className="spin"/>{progress}</div>}
 </main>;
}
